services:
  - type: web
    name: selenium-flask-app
    runtime: python  # Specifies Python as the runtime environment
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    region: oregon
